version: '3'
services:

  nginx:
    container_name: nginx
    build: requirements/nginx/
    depends_on:
      - wordpress
    ports:
      - 443:443
    # restart: always
    restart: 'no'
    networks:
      - frontend
    volumes:
      - wordpress_data:/var/www/html/

  wordpress:
    container_name: wordpress
    build: requirements/wordpress/
    depends_on:
      - mariadb
    ports:
      - 9000:9000
    # restart: always
    restart: 'no'
    networks:
      - frontend
      - backend
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
      WP_DB_HOST: ${WP_DB_HOST}
      WP_DB_PORT: ${WP_DB_PORT}
      WP_DB_NAME: ${WP_DB_NAME}
      WP_DB_USER: ${WP_DB_USER}
      WP_DB_PASS: ${WP_DB_PASS}
      WP_TITLE: ${WP_TITLE}
      WP_ADMIN: ${WP_ADMIN}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
      WP_USER: ${WP_USER}
      WP_USER_EMAIL: ${WP_USER_EMAIL}
      WP_USER_PASSWORD: ${WP_USER_PASSWORD}
    volumes:
      - wordpress_data:/var/www/html/

  mariadb:
    container_name: mariadb
    build: requirements/mariadb/
    ports:
      - 3306:3306
    # restart: always
    restart: 'no'
    networks:
      - backend
    environment:
      WP_DB_NAME: ${WP_DB_NAME}
      WP_DB_USER: ${WP_DB_USER}
      WP_DB_PASS: ${WP_DB_PASS}
    volumes:
      - mariadb_data:/var/lib/mysql

networks:
  frontend:
  backend:

volumes:
  wordpress_data:
    name: wordpress_data
    driver: local
    driver_opts:
      device: ${VOLUME_DIR}/wordpress
      o: bind
      type: none
  mariadb_data:
    name: mariadb_data
    driver: local
    driver_opts:
      device: ${VOLUME_DIR}/mariadb
      o: bind
      type: none
