version: "3"
services:
  web:
    image: alpine
    command: ping 127.0.0.1
    volumes:
      - share:/data
  db:
    image: alpine
    command: ping 127.0.0.1
    volumes:
      - share:/data
volumes:
  share:
